iterative_number_of_digits: iterative_number_of_digits.o
	g++ -o iterative_number_of_digits iterative_number_of_digits.o
iterative_factorial: iterative_factorial.o
	g++ -o iterative_factorial iterative_factorial.o
absolute_value: absolute_value.o
	g++ -o absolute_value absolute_value.o
clean:
	rm -rf *.o
